# Standards: 0.1
---
- name: Kill discord
  command: killall Discord
  register: discord_kill
  failed_when: discord_kill.rc != 0 and "No matching processes belonging to you were found" not in discord_kill.stderr
  become: "{{ (discord_user != ansible_user_id) | bool }}"
  become_user: "{{ discord_user }}"

- name: Start discord
  when: discord_started
  command: open -j /Applications/Discord.app
  become: "{{ (discord_user != ansible_user_id) | bool }}"
  become_user: "{{ discord_user }}"

...
